---
# This playbook deploys complete CI/CD pipeline, web server and Apache Kafka for simple tests

- name: Common configuration across nodes
  hosts: all

  roles:
   - common

- name: CI/CD worker node configuration
  hosts: cicd_workers
  become: yes

  vars:
    jenkins_hostname: ubuntu-worker
    java_packages: openjdk-8-jdk

  roles:
   - geerlingguy.java
   - geerlingguy.jenkins
   - exposejenkins


